"""Stress-test the three fit_check v0 regexes against the corpus and
synthetic probes. Read-only — does not modify any regex.

Outputs a markdown report on stdout (also captured into FITCHECK_AUDIT.md
by a wrapper, see report build at the end of this file).
"""
from __future__ import annotations

import json
import re
import sys
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
CHUNKS = REPO / "audits/puzzlebook35/corpus/puzzlebook_raw_chunks_v1.jsonl"

YEAR_RE = re.compile(r"\b(?:19|20)\d{2}\b")
NUMBER_RE = re.compile(r"\b\d+\b")
NAME_RE = re.compile(r"\b[А-ЯA-Z][а-яa-zё]+(?:[\s\-][А-ЯA-Z][а-яa-zё]+)?\b")

REGEXES = [("when (year)", YEAR_RE), ("how_many (number)", NUMBER_RE), ("who (name)", NAME_RE)]


def load_chunks() -> list[dict]:
    return [json.loads(l) for l in CHUNKS.open(encoding="utf-8") if l.strip()]


def per_chunk_stats(chunks: list[dict]) -> dict:
    """For each regex × chunk: count matches, unique matches."""
    out = {}
    for label, rx in REGEXES:
        per_chunk = []
        all_matches = []
        for ch in chunks:
            m = rx.findall(ch["content"])
            per_chunk.append({
                "chunk_id": ch["chunk_id"],
                "section": "/".join(ch["section_path"]),
                "match_count": len(m),
                "unique_matches": sorted(set(m)),
            })
            all_matches.extend(m)
        chunks_with_match = sum(1 for r in per_chunk if r["match_count"] > 0)
        out[label] = {
            "rx_pattern": rx.pattern,
            "chunks_with_match": chunks_with_match,
            "chunks_total": len(chunks),
            "total_matches": len(all_matches),
            "unique_matches_global": Counter(all_matches),
            "per_chunk": per_chunk,
        }
    return out


PROBES = [
    # YEAR_RE probes
    ("year", "Книга вышла в 2025 году", "real year"),
    ("year", "В файле 2024 строки кода", "year-shaped count, not a year"),
    ("year", "Период 1995-2010", "two year-shaped numbers, neither is a publication date"),
    ("year", "version 1.10.5", "version number, no year"),
    ("year", "Эпоха 1812", "historical year before regex range"),
    ("year", "В 2020-х годах", "decade reference"),
    ("year", "20030 строк", "boundary: 5-digit number starting with 20"),
    ("year", "ASCII код 80, 114, 111", "Q22 actual decoy class"),
    ("year", "Файл загружен в 2008-м", "real year"),
    ("year", "1999rps", "year + suffix without word boundary"),
    # NUMBER_RE probes
    ("number", "Простой текст без чисел", "negative control"),
    ("number", "Глава пять", "spelled-out number"),
    ("number", "1. Первый пункт списка", "list marker, not a count"),
    ("number", "Версия 3.10", "version, contains digits"),
    ("number", "В книге 50 задач", "real count"),
    ("number", "0", "single zero"),
    ("number", "В 1812 году было 2 битвы", "year + count mixed"),
    # NAME_RE probes
    ("name", "Лев Толстой", "real two-word name"),
    ("name", "Привет, мир", "sentence-initial common word, not a name"),
    ("name", "Python и Java", "language names, sentence-initial"),
    ("name", "Visual Studio Code", "product name, three caps tokens"),
    ("name", "Уайтсайд М.", "real surname + initial"),
    ("name", "Книга. Глава. Параграф.", "three sentence-initial words separated by periods"),
    ("name", "Mat Whiteside", "Latin two-word name"),
    ("name", "В Python используется", "language name mid-sentence + sentence-initial"),
    ("name", "PyCharm – jetbrains.com", "product name, no person"),
    ("name", "К этой книге", "preposition + capitalized"),
]


def run_probes() -> list[dict]:
    out = []
    for kind, text, comment in PROBES:
        if kind == "year":
            rx = YEAR_RE
        elif kind == "number":
            rx = NUMBER_RE
        else:
            rx = NAME_RE
        matches = rx.findall(text)
        out.append({
            "kind": kind,
            "input": text,
            "comment": comment,
            "matches": matches,
            "count": len(matches),
        })
    return out


def render_md(stats: dict, probes: list[dict]) -> str:
    lines = []
    lines.append("# FITCHECK_AUDIT — over-match audit of v0 regexes")
    lines.append("")
    lines.append("Generated by `audit_fitcheck.py`. Do not edit by hand.")
    lines.append("")
    lines.append("Three fit_check v0 regexes audited against:")
    lines.append("")
    lines.append("- The 30 raw chunks in `puzzlebook_raw_chunks_v1.jsonl`.")
    lines.append("- A small set of synthetic probes (positive controls + edge cases).")
    lines.append("")
    lines.append("Goal: quantify over-match before the rules are extended to "
                 "currently-skipped intents (`what`/`why`/`how`). Naively reusing "
                 "the same regex idiom there would inherit any defects found here.")
    lines.append("")

    for label, rx in REGEXES:
        s = stats[label]
        lines.append(f"## {label} — `{s['rx_pattern']}`")
        lines.append("")
        lines.append(f"- chunks with ≥1 match: **{s['chunks_with_match']} / {s['chunks_total']}**")
        lines.append(f"- total matches across corpus: **{s['total_matches']}**")
        lines.append(f"- unique match strings: **{len(s['unique_matches_global'])}**")
        lines.append("")
        lines.append("Top 15 most frequent unique matches in corpus:")
        lines.append("")
        lines.append("| match | count |")
        lines.append("|---|---|")
        for tok, n in s["unique_matches_global"].most_common(15):
            display = tok.replace("|", "\\|")
            lines.append(f"| `{display}` | {n} |")
        lines.append("")
        lines.append("Per-chunk breakdown (only chunks with matches):")
        lines.append("")
        lines.append("| chunk_id | section | count | sample unique |")
        lines.append("|---|---|---|---|")
        for r in s["per_chunk"]:
            if r["match_count"] == 0:
                continue
            sample = ", ".join(f"`{m}`" for m in r["unique_matches"][:6])
            if len(r["unique_matches"]) > 6:
                sample += f" … (+{len(r['unique_matches']) - 6})"
            section = r["section"].replace("|", "\\|")
            lines.append(f"| {r['chunk_id']} | {section} | {r['match_count']} | {sample} |")
        lines.append("")

    lines.append("## Synthetic probes")
    lines.append("")
    lines.append("Crafted strings to probe regex behaviour at known edge cases.")
    lines.append("`✓` = expected to match (positive control). `✗` = should not match "
                 "but does = over-match (failure). `−` = correctly does not match.")
    lines.append("")

    expected = {
        "Книга вышла в 2025 году": "✓",
        "В файле 2024 строки кода": "✗",
        "Период 1995-2010": "✗",
        "version 1.10.5": "−",
        "Эпоха 1812": "−",
        "В 2020-х годах": "✓",
        "20030 строк": "−",
        "ASCII код 80, 114, 111": "−",
        "Файл загружен в 2008-м": "✓",
        "1999rps": "✓",
        "Простой текст без чисел": "−",
        "Глава пять": "−",
        "1. Первый пункт списка": "✗",
        "Версия 3.10": "✗",
        "В книге 50 задач": "✓",
        "0": "✓",
        "В 1812 году было 2 битвы": "✓",
        "Лев Толстой": "✓",
        "Привет, мир": "✗",
        "Python и Java": "✗",
        "Visual Studio Code": "✗",
        "Уайтсайд М.": "✓",
        "Книга. Глава. Параграф.": "✗",
        "Mat Whiteside": "✓",
        "В Python используется": "✗",
        "PyCharm – jetbrains.com": "✗",
        "К этой книге": "✗",
    }

    lines.append("| kind | input | matches | n | expected | verdict |")
    lines.append("|---|---|---|---|---|---|")
    for p in probes:
        m = ", ".join(f"`{x}`" for x in p["matches"]) if p["matches"] else "∅"
        exp_label = expected.get(p["input"], "?")
        actual_outcome = "match" if p["count"] > 0 else "no match"
        if exp_label == "✓":
            verdict = "✓" if p["count"] > 0 else "✗ (false-negative)"
        elif exp_label == "✗":
            verdict = "✗ (over-match)" if p["count"] > 0 else "✓"
        elif exp_label == "−":
            verdict = "✓" if p["count"] == 0 else "✗ (over-match)"
        else:
            verdict = actual_outcome
        comment_md = p["comment"].replace("|", "\\|")
        input_md = p["input"].replace("|", "\\|")
        lines.append(f"| {p['kind']} | `{input_md}` | {m} | {p['count']} | {exp_label} | {verdict}: {comment_md} |")
    lines.append("")

    yr = stats["when (year)"]
    nm = stats["how_many (number)"]
    nn = stats["who (name)"]
    over_year = sum(1 for p in probes if p["kind"] == "year" and expected.get(p["input"]) == "✗" and p["count"] > 0)
    over_num = sum(1 for p in probes if p["kind"] == "number" and expected.get(p["input"]) == "✗" and p["count"] > 0)
    over_name = sum(1 for p in probes if p["kind"] == "name" and expected.get(p["input"]) == "✗" and p["count"] > 0)
    fn_year = sum(1 for p in probes if p["kind"] == "year" and expected.get(p["input"]) == "✓" and p["count"] == 0)

    lines.append("## Findings")
    lines.append("")
    lines.append("### `who` (name) — informationally useless on this corpus")
    lines.append("")
    lines.append(f"Matches in **{nn['chunks_with_match']} / {nn['chunks_total']}** chunks "
                 f"(100%). {nn['total_matches']} total matches, {len(nn['unique_matches_global'])} unique.")
    lines.append("")
    lines.append("Top hits are not names: `Выход`, `Вход`, `Python`, `Если`, `Пример`, "
                 "`Функция`, `Имя`, `Тип`, `Заготовка`, `Здесь`. These come from "
                 "table column headers, example labels (`Вход:`/`Выход:`), Python "
                 "identifiers, sentence-initial words after `.`, and reserved words.")
    lines.append("")
    lines.append("Implication: **`fit_status=match` is the foregone outcome for any "
                 "intent=who question on this corpus.** `mismatch` cannot be reached. "
                 "Q7's `match → hit` was not a coincidence — it is structurally "
                 "guaranteed by the corpus + this regex.")
    lines.append("")
    lines.append(f"Synthetic probes confirm: **{over_name} / {sum(1 for p in probes if p['kind']=='name' and expected.get(p['input'])=='✗')} "
                 "negative-control inputs over-match** (sentence-initial common words, "
                 "language/product names, mid-sentence capitalized tokens).")
    lines.append("")
    lines.append("### `how_many` (number) — too broad to discriminate")
    lines.append("")
    lines.append(f"Matches in **{nm['chunks_with_match']} / {nm['chunks_total']}** chunks "
                 f"({100 * nm['chunks_with_match'] // nm['chunks_total']}%). "
                 f"{nm['total_matches']} total matches.")
    lines.append("")
    lines.append("Top hits are not counts: `1`, `2`, `3`, … — these are mostly list "
                 "markers (`1. Первый…`), version strings (`3.10`), example data "
                 "literals (`[1, 2, 3]`), and ASCII codes inside the Morse-code task. "
                 "Almost any prose chunk and every code-bearing chunk match.")
    lines.append("")
    lines.append("Implication: **`fit_status=match` happens for ~73% of chunks regardless "
                 "of question semantics.** When Q5 or Q14 returns `match`, this is not "
                 "evidence that the chunk contains a count answer; it is evidence that "
                 "the chunk contains *any* digit. Distinguishing 'count answer' from "
                 "'incidental digit' is not done.")
    lines.append("")
    lines.append(f"Synthetic probes: **{over_num} negative-control over-matches** "
                 "(list markers, version numbers).")
    lines.append("")
    lines.append("### `when` (year) — tight on this corpus, but coincidentally")
    lines.append("")
    lines.append(f"Matches in **{yr['chunks_with_match']} / {yr['chunks_total']}** chunks. "
                 "Q22's `fit_refuse` works because the corpus simply does not contain any "
                 "`19xx`/`20xx` token in pp.12–38.")
    lines.append("")
    lines.append(f"Synthetic probes: **{over_year} over-matches** on year-shaped non-years "
                 f"(counts, ranges, decades), and **{fn_year} false-negative** on "
                 "year-with-suffix.")
    lines.append("")
    lines.append("Implication: this regex is **the only one of the three that could "
                 "plausibly refuse** — but only when no year-shaped number appears for "
                 "any reason. On a corpus with code containing magic numbers (e.g., "
                 "`port=1999`, `BUFFER_SIZE=2048`), it would lose this property "
                 "immediately. Q22 audit row's machine-verifiable check (NOTES §3) "
                 "is more robust than the bare regex because it operates on "
                 "downstream-effective-k content with explicit hit listing — "
                 "but the regex itself is brittle.")
    lines.append("")
    lines.append("## Recommendations (do not implement here — record only)")
    lines.append("")
    lines.append("1. **`who` regex is unfit for purpose** on this corpus. Before extending "
                 "fit_check or relying on `match → hit` for any intent=who question, the "
                 "rule needs a fundamentally different design: stop-word filter for "
                 "sentence-initial common words, NER, or context-aware patterns "
                 "(e.g., 'имя автора' / 'написал' / 'by' as triggers).")
    lines.append("2. **`how_many` regex needs context.** Distinguishing count answers from "
                 "list markers / version strings / data literals requires either "
                 "question-conditioned matching (does any number co-occur with the "
                 "question's noun?) or a stop-list of known non-counts.")
    lines.append("3. **`when` regex is acceptable** as-is for refuse-on-no-year, but the "
                 "match→hit branch is brittle (year-shaped count → false hit). Could be "
                 "tightened with adjacency context (`год`/`году`/`year` within ±N tokens).")
    lines.append("4. **Naively cloning these regexes for `what`/`why`/`how`** would inherit "
                 "the worst properties of #1 and #2: regexes that match almost "
                 "everything in any prose corpus. The fit_check extension needs a "
                 "different model class, not more of the same.")
    lines.append("5. **Q7 audit-row prediction reframed:** the `lexical_pattern_overmatch` "
                 "failure mode (NOTES §5) is not just a `who` problem — it is a "
                 "general property of bare regex fit_check. Two of three v0 rules "
                 "exhibit it. Only one (`when`) avoids it, by accident of corpus content.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("Regenerate this report: `python audits/puzzlebook35/baseline_v0/audit_fitcheck.py > audits/puzzlebook35/baseline_v0/FITCHECK_AUDIT.md`")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    chunks = load_chunks()
    stats = per_chunk_stats(chunks)
    probes = run_probes()
    print(render_md(stats, probes))
    return 0


if __name__ == "__main__":
    sys.exit(main())
